title: Tsung-Lun Lee
email: tllee@umich.edu
description: >- # this means to ignore newlines until "baseurl:"
Tsung-Lun Lee's personal website. Currently a graduate student in the Chemical Engineering Department at UT Austin, studying colloidal interactions and assembly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tllee-d.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: tllee-d

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
